all: s3 ec2 simpledb

s3:
	(cd amazon/s3/; ../../_utils/create-pages.pl Amazon S3 operations.ini; cd -)

ec2:
	(cd amazon/ec2/; ../../_utils/create-pages.pl Amazon EC2 operations.ini; cd -)

simpledb:
	(cd amazon/simpledb/; ../../_utils/create-pages.pl Amazon SimpleDB operations.ini; cd -)

commit:
	git commit -m 'AutoGenerated: Update all of the HTML operations pages' -a
