AMAZON_SERVICES=autoscaling cloudformation cloudfront cloudsearch cloudwatch dynamodb ec2 elasticache elasticbeanstalk elb emr fps glacier iam imd importexport rds route53 s3 ses simpledb sns sqs storagegateway sts swf

OPENSTACK_SERVICES=

all: $(AMAZON_SERVICES) $(OPENSTACK_SERVICES)

$(AMAZON_SERVICES):
	mkdir -p amazon/$@
	touch amazon/$@/examples.txt
	touch amazon/$@/index.html
	./create-pages.js amazon $@

$(OPENSTACK_SERVICES):
	mkdir -p openstack/$@
	./create-pages.js openstack $@

commit:
	git commit -m 'AutoGenerated: Update all of the HTML operations pages' -a

.PHONY: $(AMAZON_SERVICES)
