## ----------------------------------------------------------------------------
#
# DO NOT EDIT THIS FILE DIRECTLY, MAKE A COPY OF IT AND USE THAT. :)
#
# This is to make sure you never commit your credentials into the repository.
#
## ----------------------------------------------------------------------------
# Please set the following ENV VARS for the specific examples:

export NODE_PATH=`pwd`/../lib

## ----------------------------------------------------------------------------
# Amazon Web Services
# http://aws.amazon.com/

export ACCESS_KEY_ID=access-key-id
export SECRET_ACCESS_KEY=secret-access-key
export AWS_ACCOUNT_ID=aws_account_id

## ----------------------------------------------------------------------------
# GreenQloud

export GREENQLOUD_ACCESS_KEY_ID=access-key-id
export GREENQLOUD_SECRET_ACCESS_KEY=secret-access-key
export GREENQLOUD_ACCOUNT_ID=

## ----------------------------------------------------------------------------
# RackspaceCloud (ToDo)

export RACKSPACECLOUD_USERNAME=username
export RACKSPACECLOUD_API_KEY=api-key

## ----------------------------------------------------------------------------
